# Generated by Django 2.1 on 2019-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=16)),
                ('Email', models.TextField(max_length=40)),
                ('Password', models.TextField(max_length=14)),
            ],
        ),
    ]
