# Generated by Django 2.1 on 2019-07-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='thoughtspost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_thoughts', models.CharField(max_length=4000)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
